166187868 tagging an article
andela/ah-backend-realers pull request #27
Opened 2019-06-20 03:16 UTC by alexxsanya

#### What does this PR do?
- enable a user to tag an article

#### Description of Task to be completed?

- add functionality to tag an article
- update article test cases

#### How should this be manually tested?
- fetch this repo locally in the terminal with `$ git fetch origin ft-tagging-articles-166187868`
- run `$ python manage.py migrate`

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?

- Story ID - [166187868](https://www.pivotaltracker.com/story/show/166187868)

2019-06-21 08:35 UTC, HabibSentongo approved these changes
The feature functions well on my side, I feel this is ready for merge.

2019-06-21 08:54 UTC, cdvx commented on authors/apps/article_tagging/views.py
> +
Please work on these codeclimate issues @alexxsanya

2019-06-21 08:55 UTC, neelxie requested changes
Tested the feature and supplying tags like symbols and numbers and it returns an error.

<img width="1172" alt="Screenshot 2019-06-21 at 11 50 41" src="https://user-images.githubusercontent.com/32802973/59910582-e4c9c600-941a-11e9-88b2-b345b778ff1f.png">

2019-06-21 10:07 UTC, merged

2019-06-23 01:54 UTC, alexxsanya commented
> Tested the feature and supplying tags like symbols and numbers and it returns an error.
> 
> <img alt="Screenshot 2019-06-21 at 11 50 41" width="1172" src="https://user-images.githubusercontent.com/32802973/59910582-e4c9c600-941a-11e9-88b2-b345b778ff1f.png">

@neelxie thanks. this was fixed